services:
  postgres:
    image: postgres:14-alpine
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
